use std::{collections::HashMap,env,fs};use std::convert::TryInto;
#[derive(Clone)]struct I{addr:u64,code:String,shape:String,target:Option<u64>,len:usize}
fn hexnums(s:&str)->String{let b=s.as_bytes();let mut o=String::new();let mut i=0;while i<b.len(){if i+2<b.len()&&b[i]==b'0'&&b[i+1]==b'x'{let mut j=i+2;while j<b.len()&&b[j].is_ascii_hexdigit(){j+=1}if j>i+2{o.push_str("NUM");i=j;continue}}o.push(b[i]as char);i+=1}o}
fn nr(mut s:String)->String{loop{let Some(r)=s.find("rip+0x").or_else(||s.find("rip-0x"))else{break};let st=r+3;let mut en=st+3;while en<s.len()&&s.as_bytes()[en].is_ascii_hexdigit(){en+=1}s.replace_range(st..en,"+DISP");}s}
fn parse(p:&str,start:u64,end:u64)->Vec<I>{let t=fs::read_to_string(p).unwrap();let mut tmp=Vec::<(u64,String,Option<u64>)>::new();for l in t.lines(){let Some((a,r))=l.split_once(":\t")else{continue};let a=a.trim();if a.is_empty()||!a.chars().all(|c|c.is_ascii_hexdigit()){continue}let x=u64::from_str_radix(a,16).unwrap();if x<start||x>=end{continue}let m=r.split_whitespace().next().unwrap_or("");let comment_target=r.split("# 0x").nth(1).and_then(|z|z.split_whitespace().next()).and_then(|z|u64::from_str_radix(z,16).ok());let direct_target=if m=="call"||m=="jmp"||m.starts_with('j'){r.split_whitespace().nth(1).map(|z|z.trim_end_matches(',').trim_start_matches("0x")).and_then(|z|u64::from_str_radix(z,16).ok())}else{None};let target=comment_target.or(direct_target);tmp.push((x,r.to_string(),target));}let mut v=Vec::new();for k in 0..tmp.len(){let(a,r,target)=&tmp[k];let next=if k+1<tmp.len(){tmp[k+1].0}else{end};let m=r.split_whitespace().next().unwrap_or("");if m=="int3"||m=="(bad)"||m=="nop"||m.starts_with("nopw"){continue}let mut c=nr(r.split('#').next().unwrap_or("").trim().to_string());if m=="call"||m=="jmp"||m.starts_with('j'){if let Some(sp)=c.find(char::is_whitespace){let op=c[sp..].trim();let f=op.split_whitespace().next().unwrap_or("").trim_end_matches(',');let n=f.trim_start_matches("0x");if !n.is_empty()&&n.chars().all(|q|q.is_ascii_hexdigit()){c=format!("{m} ADDR{}",&op[f.len()..]);}}}v.push(I{addr:*a,shape:hexnums(&c),code:c,target:*target,len:(next-a)as usize});}v}
fn align(a:&[I],b:&[I])->Vec<(Option<usize>,Option<usize>)>{let(n,m)=(a.len(),b.len());let w=m+1;let mut d=vec![0u16;(n+1)*w];for i in 0..=n{d[i*w]=i as u16}for j in 0..=m{d[j]=j as u16}for i in 1..=n{for j in 1..=m{let c=if a[i-1].shape==b[j-1].shape{0}else{1};d[i*w+j]=(d[(i-1)*w+j-1]+c).min((d[(i-1)*w+j]+1).min(d[i*w+j-1]+1));}}let(mut i,mut j)=(n,m);let mut o=Vec::new();while i>0||j>0{if i>0&&j>0{let c=if a[i-1].shape==b[j-1].shape{0}else{1};if d[i*w+j]==d[(i-1)*w+j-1]+c{o.push((Some(i-1),Some(j-1)));i-=1;j-=1;continue}}if i>0&&d[i*w+j]==d[(i-1)*w+j]+1{o.push((Some(i-1),None));i-=1}else{o.push((None,Some(j-1)));j-=1}}o.reverse();o}
struct Pe{b:Vec<u8>,base:u64,s:Vec<(u64,u64,usize,usize)>}impl Pe{fn load(p:&str)->Self{let b=fs::read(p).unwrap();let e=u32::from_le_bytes(b[0x3c..0x40].try_into().unwrap())as usize;let n=u16::from_le_bytes(b[e+6..e+8].try_into().unwrap())as usize;let os=u16::from_le_bytes(b[e+20..e+22].try_into().unwrap())as usize;let o=e+24;let base=u64::from_le_bytes(b[o+24..o+32].try_into().unwrap());let z=o+os;let mut s=Vec::new();for i in 0..n{let q=z+i*40;let vs=u32::from_le_bytes(b[q+8..q+12].try_into().unwrap())as u64;let va=u32::from_le_bytes(b[q+12..q+16].try_into().unwrap())as u64;let rs=u32::from_le_bytes(b[q+16..q+20].try_into().unwrap())as usize;let rp=u32::from_le_bytes(b[q+20..q+24].try_into().unwrap())as usize;s.push((va,vs.max(rs as u64),rp,rs));}Self{b,base,s}}fn bytes(&self,a:u64,n:usize)->Option<&[u8]>{let r=a.checked_sub(self.base)?;for&(v,z,p,rs)in &self.s{if r>=v&&r+n as u64<=v+z{let o=p+(r-v)as usize;if o+n<=p+rs{return self.b.get(o..o+n)}}}None}}
fn find_disp(bytes:&[u8],v:i64)->Option<(usize,usize)>{let q=(v as i32).to_le_bytes();let p:Vec<_>=bytes.windows(4).enumerate().filter(|(_,x)|*x==q).map(|(i,_)|i).collect();if p.len()==1{return Some((p[0],4))}if (-128..=127).contains(&v){let c=v as i8 as u8;let p:Vec<_>=bytes.iter().enumerate().filter(|(_,x)|**x==c).map(|(i,_)|i).collect();if p.len()==1{return Some((p[0],1))}}None}
fn put_disp(bytes:&mut[u8],at:usize,n:usize,v:i64){if n==4{bytes[at..at+4].copy_from_slice(&(v as i32).to_le_bytes())}else{bytes[at]=v as i8 as u8}}
fn const_width(code:&str)->usize{if !(code.contains("rip+")||code.contains("rip-")){return 0}if code.contains("XMMWORD PTR"){16}else if code.contains("QWORD PTR"){8}else if code.contains("DWORD PTR")||code.starts_with("movss ")||code.starts_with("mulss ")||code.starts_with("addss ")||code.starts_with("subss ")||code.starts_with("divss ")||code.starts_with("comiss "){4}else{0}}
fn as_pat(b:&[u8])->String{b.iter().map(|x|format!("{x:02X}")).collect::<Vec<_>>().join(" ")}
fn main(){let a:Vec<String>=env::args().skip(1).collect();if a.len()!=9{eprintln!("usage: islandgen OLD.exe NEW.exe OLD.s NEW.s OLD_START OLD_END NEW_START NEW_END FIELD.tsv");std::process::exit(2)}let hx=|s:&str|u64::from_str_radix(s.trim_start_matches("0x"),16).unwrap();let(os,oe,ns,ne)=(hx(&a[4]),hx(&a[5]),hx(&a[6]),hx(&a[7]));let op=Pe::load(&a[0]);let np=Pe::load(&a[1]);let oi=parse(&a[2],os,oe);let ni=parse(&a[3],ns,ne);let mut blob=op.bytes(os,(oe-os)as usize).unwrap().to_vec();let mut byaddr=HashMap::new();for x in &oi{byaddr.insert(x.addr,x.clone());}let mut field_manifest=Vec::<(usize,u64,usize,i64,i64)>::new();
 let mut field_failed=0;for(lineno,l)in fs::read_to_string(&a[8]).unwrap().lines().enumerate(){if lineno==0{continue}let f:Vec<_>=l.split('\t').collect();if f.len()<7{continue}let ctx=f[2];if ctx.starts_with("rbp")||ctx.starts_with("rsp")||ctx=="rax-OFF"{continue}let ia=hx(f[0]);let ov=i64::from_str_radix(f[3].trim_start_matches("0x"),16).unwrap();let nv=i64::from_str_radix(f[4].trim_start_matches("0x"),16).unwrap();let Some(ins)=byaddr.get(&ia)else{field_failed+=1;continue};let off=(ia-os)as usize;let ib=&mut blob[off..off+ins.len];if let Some((p,n))=find_disp(ib,ov){put_disp(ib,p,n,nv);field_manifest.push(((ia-os)as usize+p,ia,n,ov,nv))}else{field_failed+=1;}}
 let root_extra_fields:[(u64,i64,i64);11]=[(0x1405ee206,0x1378,0x1280),(0x1405ee2d6,0x1378,0x1280),(0x1405eea94,0x1378,0x1280),(0x1405eef14,0x18c0,0x1760),(0x1405ef055,0x18c0,0x1760),(0x1405ef335,0x15d8,0x1478),(0x1405ef480,0x18d0,0x1780),(0x1405ef4c5,0x1c78,0x1b40),(0x1405ef53b,0x1cb0,0x1b78),(0x1405efa22,0x15fc,0x149c),(0x1405efee8,0x690,0x1ce0)];for(site,ov,nv)in root_extra_fields{let ins=byaddr.get(&site).unwrap();let p0=(site-os)as usize;let(p,z)=find_disp(&blob[p0..p0+ins.len],ov).expect("root extra field displacement");put_disp(&mut blob[p0..p0+ins.len],p,z,nv);field_manifest.push((p0+p,site,z,ov,nv));}
 let al=align(&oi,&ni);let mut rel=Vec::<(usize,u64,String)>::new();let mut handled=std::collections::HashSet::new();let mut pool=HashMap::<u64,(usize,usize)>::new();for(x,y)in al{let(Some(i),Some(j))=(x,y)else{continue};let(o,n)=(&oi[i],&ni[j]);if o.shape!=n.shape{continue}let is_call=o.code.starts_with("call ADDR");let is_rip=o.code.contains("rip+")||o.code.contains("rip-");if !(is_call||is_rip){continue}let(Some(ot),Some(nt))=(o.target,n.target)else{continue};if is_call&&ot==0x1405e1000{let next=o.addr+o.len as u64;let od=ot as i64-next as i64;let raw=op.bytes(o.addr,o.len).unwrap();if let Some((p,4))=find_disp(raw,od){rel.push(((o.addr-os)as usize+p,0x140845190-np.base,"call-manual".into()));handled.insert(o.addr);}continue};if !is_call&&nt<np.base{continue}let next=o.addr+o.len as u64;let od=ot as i64-next as i64;let raw=op.bytes(o.addr,o.len).unwrap();if let Some((p,z))=find_disp(raw,od){if z==4{let w=const_width(&o.code);if is_rip&&w>0{while blob.len()%16!=0{blob.push(0xCC)}let q=blob.len();blob.extend_from_slice(op.bytes(ot,w).unwrap());pool.insert(ot,(q,w));rel.push(((o.addr-os)as usize+p,q as u64,"const".into()));}else{let mapped=if is_call&&ot==0x1401850f0{0x14042bcb0-np.base}else if is_call&&ot==0x1405deff0{0x140843150-np.base}else if is_call&&ot==0x1418544ac{0x14195dd00-np.base}else if is_call&&ot==0x1405e1000{0x140845190-np.base}else{nt-np.base};rel.push(((o.addr-os)as usize+p,mapped,if is_call{"call"}else{"rip"}.into()));}handled.insert(o.addr);}}}
 for o in &oi{if handled.contains(&o.addr){continue}let w=const_width(&o.code);if w==0{continue}let Some(t)=o.target else{continue};let po=if let Some(&(p,have))=pool.get(&t){if have>=w{p}else{while blob.len()%16!=0{blob.push(0xCC)}let q=blob.len();let Some(src)=op.bytes(t,w)else{continue};blob.extend_from_slice(src);pool.insert(t,(q,w));q}}else{while blob.len()%16!=0{blob.push(0xCC)}let p=blob.len();let Some(src)=op.bytes(t,w)else{continue};blob.extend_from_slice(src);pool.insert(t,(p,w));p};let next=o.addr+o.len as u64;let od=t as i64-next as i64;let raw=op.bytes(o.addr,o.len).unwrap();if let Some((p,z))=find_disp(raw,od){if z==4{rel.push(((o.addr-os)as usize+p,po as u64,"const".into()));handled.insert(o.addr);}}}
 // Resolve three root calls whose current counterparts were split/inlined enough to defeat the generic aligner.
 let manual_current:[(u64,u64);2]=[(0x1405ee1f9,0x140846010),(0x1405ee201,0x140850e50)];
 for(site,target)in manual_current{let ins=byaddr.get(&site).unwrap();let ot=ins.target.unwrap();let od=ot as i64-(site+ins.len as u64)as i64;let raw=op.bytes(site,ins.len).unwrap();let(p,z)=find_disp(raw,od).expect("manual root call displacement");assert_eq!(z,4);rel.push(((site-os)as usize+p,target-np.base,"call-manual".into()));handled.insert(site);}
 // Old wrappers use an output-pointer interpolation ABI that no longer exists.  Keep
 // their field selection and unit conversion, but route the interpolation through a
 // measured adapter that calls the current scalar helper and writes xmm0 to r8.
 while blob.len()%16!=0{blob.push(0xCC)}
 let interpolation_adapter=blob.len();
 blob.extend_from_slice(&[0x48,0x83,0xEC,0x38,0x4C,0x89,0x44,0x24,0x20,0xE8,0,0,0,0,0x48,0x8B,0x44,0x24,0x20,0xF3,0x0F,0x11,0x00,0x48,0x83,0xC4,0x38,0xC3]);
 rel.push((interpolation_adapter+10,0x14042bcb0-np.base,"call-manual".into()));
 // The January executable initializes the removed helper's model block to
 // max=5.0, step=5.0, threshold=25.0, disabled=0.  Keep that indirect data
 // closure in-island instead of reading incompatible current defaults.
 while blob.len()%16!=0{blob.push(0xCC)}
 let initializer_shadow=blob.len();
 blob.resize(initializer_shadow+0x7a4,0);
 blob[initializer_shadow+0x788..initializer_shadow+0x78c].copy_from_slice(&0x40a00000u32.to_le_bytes());
 blob[initializer_shadow+0x78c..initializer_shadow+0x790].copy_from_slice(&0x40a00000u32.to_le_bytes());
 blob[initializer_shadow+0x790..initializer_shadow+0x794].copy_from_slice(&0x41c80000u32.to_le_bytes());
 blob[initializer_shadow+0x7a0..initializer_shadow+0x7a4].copy_from_slice(&0u32.to_le_bytes());
 // Copy the January-only helper, averaging helper, initializer, and wrapper closure.
 let helper_defs:[(u64,u64,u64);13]=[(0x1405edcf0,0x1405ede00,0x1405eee17),(0x1405e7730,0x1405e77f2,0x1405ef4a2),(0x1405ede00,0x1405edeac,0x1405edf56),(0x1413be660,0x1413be695,0x1405ee8d1),(0x1413be660,0x1413be695,0x1405eef6e),(0x1413be750,0x1413be785,0x1405ef0f8),(0x1413be810,0x1413be845,0x1405ef2e9),(0x1413be850,0x1413be893,0x1405ef2c8),(0x1413be8a0,0x1413be8d5,0x1405ef330),(0x1413be900,0x1413be955,0x1405ee7ff),(0x1413be960,0x1413be995,0x1405ef2e2),(0x1413bea20,0x1413bea55,0x1405ee772),(0x1413beaa0,0x1413bead5,0x1405eedcc)];
 let helper_fields:[(u64,i64,i64);27]=[(0x1405edd0d,0x1640,0x14dc),(0x1405edd19,0x1910,0x16c0),(0x1405edd5e,0x145c,0x12fc),(0x1405edd67,0x1464,0x1304),(0x1405edd79,0x1640,0x14dc),(0x1405edd9b,0x1460,0x1300),(0x1405edde9,0x1640,0x14dc),(0x1405eddf6,0x1640,0x14dc),(0x1405e7787,0x6c0,0x6b8),(0x1405ede0b,0x1378,0x1280),(0x1405ede1b,0x1378,0x1280),(0x1405ede30,0x1378,0x1280),(0x1405ede43,0x1378,0x1280),(0x1405ede5a,0x18cc,0x176c),(0x1405ede67,0x18ca,0x176a),(0x1413be671,0x5a0,0x18d8),(0x1413be761,0x590,0x1880),(0x1413be821,0x288,0xab8),(0x1413be86e,0x658,0x1b88),(0x1413be885,0x660,0x1bd8),(0x1413be8b1,0x570,0x1818),(0x1413be904,0xa0,0x248),(0x1413be90c,0xa4,0x24c),(0x1413be934,0x688,0x1c90),(0x1413be971,0x290,0xb08),(0x1413bea31,0x720,0x1e90),(0x1413beab1,0x6b8,0x1d08)];
 let mut helper_regions=Vec::new();
 for(hs,he,callsite)in helper_defs{
  while blob.len()%16!=0{blob.push(0xCC)}
  let bo=blob.len();
  let helper_shift=if hs==0x1405edcf0{
   assert_eq!(op.bytes(hs,4).unwrap(),&[0x4c,0x8b,0x51,0x40]);
   blob.extend_from_slice(&[0x4c,0x8d,0x15,0,0,0,0]);
   blob.extend_from_slice(op.bytes(hs+4,(he-hs-4)as usize).expect("helper PE bytes"));
   rel.push((bo+3,initializer_shadow as u64,"const".into()));
   3usize
  }else{
   blob.extend_from_slice(op.bytes(hs,(he-hs)as usize).expect("helper PE bytes"));
   0usize
  };
  let hi=parse(&a[2],hs,he);
  for&(site,ov,nv)in &helper_fields{if site<hs||site>=he{continue}let ins=hi.iter().find(|x|x.addr==site).unwrap_or_else(||panic!("missing helper instruction 0x{:x}",site));let p0=bo+(site-hs)as usize+helper_shift;let(p,z)=find_disp(&blob[p0..p0+ins.len],ov).expect("helper field displacement");put_disp(&mut blob[p0..p0+ins.len],p,z,nv);field_manifest.push((p0+p,site,z,ov,nv));}
  let root=byaddr.get(&callsite).unwrap_or_else(||panic!("missing root callsite 0x{:x}",callsite));let ot=root.target.unwrap_or_else(||panic!("missing root call target 0x{:x}",callsite));let od=ot as i64-(callsite+root.len as u64)as i64;let raw=op.bytes(callsite,root.len).unwrap();let(p,z)=find_disp(raw,od).expect("root to helper displacement");assert_eq!(z,4);let root_reloc=(callsite-os)as usize+p;rel.retain(|x|x.0!=root_reloc);rel.push((root_reloc,bo as u64,"island-call".into()));handled.insert(callsite);helper_regions.push((hs,he,bo,hi,helper_shift));
 }
 // Relocate helper calls and copy their floating constants into the island pool.
 for(hs,_he,bo,hi,helper_shift)in &helper_regions{for ins in hi{if *helper_shift!=0&&ins.addr==*hs{continue}let is_call=ins.code.starts_with("call ADDR");let w=const_width(&ins.code);if !is_call&&w==0{continue}let Some(t)=ins.target else{continue};let raw=op.bytes(ins.addr,ins.len).unwrap();let od=t as i64-(ins.addr+ins.len as u64)as i64;let Some((p,z))=find_disp(raw,od)else{continue};if z!=4{continue}let target=if is_call{if t==0x1401850b0{interpolation_adapter as u64}else if t==0x1401850f0{0x14042bcb0-np.base}else if t==0x1405d9ed0{0x14083dc30-np.base}else if t==0x1405da030{0x14083dd90-np.base}else if t==0x1405d9e90{0x14083dbf0-np.base}else if t==0x1405d9e20{0x14083db80-np.base}else{continue}}else{if let Some(&(q,have))=pool.get(&t){if have>=w{q as u64}else{while blob.len()%16!=0{blob.push(0xCC)}let q=blob.len();blob.extend_from_slice(op.bytes(t,w).unwrap());pool.insert(t,(q,w));q as u64}}else{while blob.len()%16!=0{blob.push(0xCC)}let q=blob.len();blob.extend_from_slice(op.bytes(t,w).unwrap());pool.insert(t,(q,w));q as u64}};rel.push((bo+(ins.addr-hs)as usize+*helper_shift+p,target,if is_call{"call-manual".into()}else{"const".into()}));}}
 // Resolve January call sites that have no instruction-aligned current counterpart.
 let fallback_calls:[(u64,u64);3]=[(0x1401850f0,0x14042bcb0),(0x1405e90b0,0x14084f390),(0x1405e1080,0x140845210)];
 for ins in &oi{if handled.contains(&ins.addr)||!ins.code.starts_with("call ADDR"){continue}let Some(old_target)=ins.target else{continue};let Some((_,current_target))=fallback_calls.iter().find(|(old,_)|*old==old_target)else{continue};let old_delta=old_target as i64-(ins.addr+ins.len as u64)as i64;let raw=op.bytes(ins.addr,ins.len).unwrap();let(p,z)=find_disp(raw,old_delta).expect("fallback call displacement");assert_eq!(z,4);rel.push(((ins.addr-os)as usize+p,*current_target-np.base,"call-manual".into()));handled.insert(ins.addr);}
 // Calls from copied January wrappers to the compatibility adapter stay in-island.
 for relocation in &mut rel{if relocation.2=="call-manual"&&relocation.1==interpolation_adapter as u64{relocation.2="island-call".into();}}
 // Route every external call through an in-island absolute thunk, so allocation need not land within +/-2 GiB of Trackmania.exe.
 let mut thunks=HashMap::<u64,usize>::new();let mut abs64=Vec::<(usize,u64)>::new();for i in 0..rel.len(){if rel[i].2!="call"&&rel[i].2!="call-manual"{continue}let rva=rel[i].1;let to=if let Some(&q)=thunks.get(&rva){q}else{while blob.len()%16!=0{blob.push(0xCC)}let q=blob.len();blob.extend_from_slice(&[0x48,0xB8,0,0,0,0,0,0,0,0,0xFF,0xE0]);thunks.insert(rva,q);abs64.push((q+2,rva));q};rel[i].1=to as u64;rel[i].2="island-call".into();}
 let mut unresolved=Vec::new();for o in &oi{let is_call=o.code.starts_with("call ADDR");let is_rip=o.code.contains("rip+")||o.code.contains("rip-");let external=o.target.map_or(false,|t|t<os||t>=oe);if external&&(is_call||is_rip)&&!handled.contains(&o.addr){unresolved.push(format!("0x{:x}\t{}\ttarget={}",o.addr,o.code,o.target.map(|t|format!("0x{t:x}")).unwrap_or_else(||"?".into())));}}
 let unresolved_call=unresolved.iter().filter(|x|x.contains("\tcall ")).count();let unresolved_rip=unresolved.len()-unresolved_call;
 field_manifest.sort_by_key(|x|x.0);for pair in field_manifest.windows(2){assert_ne!(pair[0].0,pair[1].0,"duplicate field patch offset {}",pair[0].0)}
 rel.sort_by_key(|x|x.0);for pair in rel.windows(2){assert_ne!(pair[0].0,pair[1].0,"duplicate relocation offset {}",pair[0].0)}
 let calls:Vec<_>=rel.iter().filter(|x|x.2=="island-call").collect();
 let rips:Vec<_>=rel.iter().filter(|x|x.2!="island-call").collect();
 let mut region_starts=vec![os];let mut region_ends=vec![oe];let mut region_offsets=vec![0usize];let mut region_lengths=vec![(oe-os)as usize];
 for(hs,he,bo,_hi,shift)in &helper_regions{region_starts.push(*hs);region_ends.push(*he);region_offsets.push(*bo);region_lengths.push((he-hs)as usize+*shift);}
 eprintln!("blob_bytes={} field_relocations={} field_failed={} call_relocations={} rip_relocations={} abs64_targets={} unresolved_calls={} unresolved_rip={}",blob.len(),field_manifest.len(),field_failed,calls.len(),rips.len(),abs64.len(),unresolved_call,unresolved_rip);for u in &unresolved{eprintln!("UNRESOLVED\t{u}");}
 println!("// Generated January 2022 native island: January root, initializer, old-only helpers, wrapper closure, and 2026 targets.");
 println!("const uint PROFILE_JAN2022_ISLAND_SIZE = {};",blob.len());
 println!("const uint PROFILE_JAN2022_UNRESOLVED_CALLS = {unresolved_call};");
 println!("const uint PROFILE_JAN2022_UNRESOLVED_RIP = {unresolved_rip};");
 println!("const uint PROFILE_JAN2022_FIELD_RELOCATION_COUNT = {};",field_manifest.len());
 println!("const uint PROFILE_JAN2022_CALL_RELOCATION_COUNT = {};",calls.len());
 println!("const uint PROFILE_JAN2022_RIP_RELOCATION_COUNT = {};",rips.len());
 println!("const uint PROFILE_JAN2022_INTERPOLATION_ADAPTER_OFFSET = {interpolation_adapter};");
 println!("const uint PROFILE_JAN2022_INITIALIZER_SHADOW_OFFSET = {initializer_shadow};");
 println!("const string PROFILE_JAN2022_ISLAND_BYTES = \"{}\";",as_pat(&blob));
 println!("const array<uint> PROFILE_JAN2022_FIELD_OFFSETS = {{{}}};",field_manifest.iter().map(|x|x.0.to_string()).collect::<Vec<_>>().join(","));
 println!("const array<uint64> PROFILE_JAN2022_FIELD_SOURCE_VAS = {{{}}};",field_manifest.iter().map(|x|format!("0x{:X}",x.1)).collect::<Vec<_>>().join(","));
 println!("const array<uint> PROFILE_JAN2022_FIELD_WIDTHS = {{{}}};",field_manifest.iter().map(|x|x.2.to_string()).collect::<Vec<_>>().join(","));
 println!("const array<uint64> PROFILE_JAN2022_FIELD_OLD_VALUES = {{{}}};",field_manifest.iter().map(|x|format!("0x{:X}",x.3 as u64)).collect::<Vec<_>>().join(","));
 println!("const array<uint64> PROFILE_JAN2022_FIELD_NEW_VALUES = {{{}}};",field_manifest.iter().map(|x|format!("0x{:X}",x.4 as u64)).collect::<Vec<_>>().join(","));
 println!("const array<uint> PROFILE_JAN2022_CALL_RELOC_OFFSETS = {{{}}};",calls.iter().map(|x|x.0.to_string()).collect::<Vec<_>>().join(","));
 println!("const array<uint64> PROFILE_JAN2022_CALL_TARGET_ISLAND_OFFSETS = {{{}}};",calls.iter().map(|x|format!("0x{:X}",x.1)).collect::<Vec<_>>().join(","));
 println!("const array<uint> PROFILE_JAN2022_RIP_RELOC_OFFSETS = {{{}}};",rips.iter().map(|x|x.0.to_string()).collect::<Vec<_>>().join(","));
 println!("const array<uint64> PROFILE_JAN2022_RIP_TARGET_RVAS = {{{}}};",rips.iter().map(|x|format!("0x{:X}",x.1)).collect::<Vec<_>>().join(","));
 println!("const array<bool> PROFILE_JAN2022_RIP_TARGET_IS_ISLAND = {{{}}};",rips.iter().map(|x|if x.2=="const"{"true"}else{"false"}).collect::<Vec<_>>().join(","));
 println!("const array<uint64> PROFILE_JAN2022_INIT_SOURCE_VAS = {{0x1413B4D43,0x1413B4D4D,0x1413B4D57,0x1413B4DA6}};");
 println!("const array<uint> PROFILE_JAN2022_INIT_SHADOW_OFFSETS = {{{},{},{},{}}};",initializer_shadow+0x788,initializer_shadow+0x78c,initializer_shadow+0x790,initializer_shadow+0x7a0);
 println!("const array<uint> PROFILE_JAN2022_INIT_VALUES = {{0x40A00000,0x40A00000,0x41C80000,0x00000000}};");
 println!("const array<uint64> PROFILE_JAN2022_SOURCE_REGION_START_VAS = {{{}}};",region_starts.iter().map(|x|format!("0x{x:X}")).collect::<Vec<_>>().join(","));
 println!("const array<uint64> PROFILE_JAN2022_SOURCE_REGION_END_VAS = {{{}}};",region_ends.iter().map(|x|format!("0x{x:X}")).collect::<Vec<_>>().join(","));
 println!("const array<uint> PROFILE_JAN2022_ISLAND_REGION_OFFSETS = {{{}}};",region_offsets.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(","));
 println!("const array<uint> PROFILE_JAN2022_ISLAND_REGION_LENGTHS = {{{}}};",region_lengths.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(","));
 println!("const array<uint> PROFILE_JAN2022_RELOC_OFFSETS = {{{}}};",rel.iter().map(|x|x.0.to_string()).collect::<Vec<_>>().join(","));
 println!("const array<uint64> PROFILE_JAN2022_RELOC_TARGET_RVAS = {{{}}};",rel.iter().map(|x|format!("0x{:X}",x.1)).collect::<Vec<_>>().join(","));
 println!("const array<bool> PROFILE_JAN2022_RELOC_TARGET_IS_ISLAND = {{{}}};",rel.iter().map(|x|if x.2=="const"||x.2=="island-call"{"true"}else{"false"}).collect::<Vec<_>>().join(","));
 println!("const array<uint> PROFILE_JAN2022_ABS64_OFFSETS = {{{}}};",abs64.iter().map(|x|x.0.to_string()).collect::<Vec<_>>().join(","));
 println!("const array<uint64> PROFILE_JAN2022_ABS64_TARGET_RVAS = {{{}}};",abs64.iter().map(|x|format!("0x{:X}",x.1)).collect::<Vec<_>>().join(","));
 println!("// relocation kinds: {}",rel.iter().map(|x|x.2.as_str()).collect::<Vec<_>>().join(","));
}
