[package]
name = "tmenv"
version = "0.1.0"
edition = "2021"

[dependencies]
branch = { path = "../../search/branch" }
forkoracle = { path = "../../search/forkoracle" }
fk = { path = "../../fk/fk" }
mapgeom = { path = "../../mapgeom" }
tmmaps = { path = "../../tmmaps" }
tmauto = { path = "../../tmauto" }
ghost = { path = "../../ghost" }
gbx = { path = "../../gbx" }
tmstate = { path = "../tmstate" }
tmobs = { path = "../tmobs" }
serde_json = "1"

[lib]
name = "tmenv"
path = "src/lib.rs"

[[bin]]
name = "tmenv"
path = "src/main.rs"
