//! [`EngineOracle`]: the explorer's `PlainOracle`, which is the only thing in
//! the system that can turn a candidate into a result.
//!
//! ```text
//!   ContainerTemplate + GeneratedTape --sanitize--> PreparedContainer
//!       --Patcher--> .Ghost.Gbx --server--> Verdict
//! ```
//!
//! Every arrow is somebody else's code. `Patcher` is `tmsearch`'s (and it
//! derives its bit positions by probing `ghost`'s encoder, so it cannot drift
//! from the codec); `validate_many` is `ghost`'s. This file is the wiring and
//! the rules about what may be believed.
//!
//! # What it refuses to do
//!
//! * **It does not read the declared time.** `SimResult::declared_ms` is what
//!   the FILE claims and `time_ms` is what the server SIMULATED; a patched
//!   tape inherits its template's header, so the declaration is the donor's
//!   number until something writes it. Reading it as a result is the recurring
//!   defect in this layer.
//! * **It does not accept a time from anywhere else.** There is no path in
//!   this type that produces a `Finish` without a server having simulated a
//!   file that exists on disk.

use forkoracle::inputs::Inputs;
use ghost::oracle::{validate_many, MapsMode};
use ghost::{Container, Encoding, Tape};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use tmexplore::action::Input;
use tmexplore::branch::PlainOracle;
use tmexplore::outcome::Verdict;
use tmsearch::tape::Patcher;

/// Opaque bytes from a game-recorded file. The donor's decoded inputs and
/// trajectory are never exposed through this type.
pub struct ContainerTemplate {
    bytes: Vec<u8>,
    ticks: usize,
}

impl ContainerTemplate {
    pub fn load(path: &Path) -> Result<Self, String> {
        let bytes = std::fs::read(path).map_err(|e| format!("{}: {}", path.display(), e))?;
        let tape = Tape::from_file(&path.to_string_lossy())?;
        if tape.archives.len() != 1 {
            return Err(format!(
                "{} has {} input archives; an opaque search container requires exactly one",
                path.display(),
                tape.archives.len()
            ));
        }
        Ok(Self {
            bytes,
            ticks: tape.n(),
        })
    }

    pub fn capacity(&self) -> usize {
        self.ticks
    }

    /// Replace the complete input archive with a generated tape before any
    /// search component receives the container.
    pub fn prepare(
        self,
        generated: GeneratedTape,
        out: &Path,
    ) -> Result<PreparedContainer, String> {
        if generated.len() != self.ticks {
            return Err(format!(
                "generated tape has {} ticks, container has {}",
                generated.len(),
                self.ticks
            ));
        }
        if let Some(parent) = out.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("{}: {}", parent.display(), e))?;
        }
        let source = out.with_extension("source.Ghost.Gbx");
        std::fs::write(&source, &self.bytes).map_err(|e| format!("{}: {}", source.display(), e))?;
        let container = Container::load(&source.to_string_lossy())?;
        let mut tape = Tape::from_file(&source.to_string_lossy())?;
        tape.replace_input_channels(
            &generated.inputs().steer,
            &generated.inputs().gas,
            &generated.inputs().brake,
        )?;
        let bytes = tape.inject_into(&container, Encoding::Explicit)?;
        std::fs::write(out, bytes).map_err(|e| format!("{}: {}", out.display(), e))?;
        let _ = std::fs::remove_file(&source);

        let patcher = Patcher::build(&out.to_string_lossy())?;
        if !patcher.unwritable.is_empty() {
            return Err(format!(
                "the prepared container has {} input ticks the search cannot rewrite after its prefix (first: {:?})",
                patcher.unwritable.len(),
                patcher.unwritable.first()
            ));
        }
        if patcher.template != *generated.inputs() {
            return Err("the prepared container read back a different input tape".into());
        }
        Ok(PreparedContainer {
            path: out.to_path_buf(),
            patcher,
            generated,
        })
    }
}

/// Inputs generated by our own code, never decoded from the opaque container.
#[derive(Clone)]
pub struct GeneratedTape(Inputs);

impl GeneratedTape {
    pub fn new(inputs: Inputs) -> Self {
        Self(inputs)
    }

    /// A deterministic, high-entropy steering signature with full throttle.
    /// It both sanitizes the complete donor archive and gives the fork shim an
    /// unambiguous decoded-input key.
    pub fn plumbing(ticks: usize) -> Self {
        let steer = (0..ticks)
            .map(|t| ((t as u64 * 7919 + 13) % 25) as i8 - 12)
            .collect();
        Self(Inputs {
            steer,
            gas: vec![true; ticks],
            brake: vec![false; ticks],
        })
    }

    pub fn len(&self) -> usize {
        self.0.len()
    }

    pub fn inputs(&self) -> &Inputs {
        &self.0
    }
}

/// A game-authored container whose entire input archive has been replaced.
pub struct PreparedContainer {
    path: PathBuf,
    patcher: Patcher,
    generated: GeneratedTape,
}

impl PreparedContainer {
    pub fn path(&self) -> &Path {
        &self.path
    }
}

pub struct EngineOracle {
    patcher: Arc<Patcher>,
    server: PathBuf,
    map: PathBuf,
    dir: PathBuf,
    seq: AtomicU64,
    pub calls: AtomicU64,
    prefix_ticks: AtomicU64,
    generated: GeneratedTape,
    container_path: PathBuf,
}

impl EngineOracle {
    /// Build an oracle from an already-sanitized opaque container. Neither the
    /// donor's inputs nor its recorded trajectory are available through this
    /// API; only `prepared.generated` can seed or pad a candidate.
    pub fn new(
        prepared: PreparedContainer,
        map: &Path,
        server: &Path,
        work: &Path,
    ) -> Result<EngineOracle, String> {
        std::fs::create_dir_all(work).map_err(|e| format!("{}: {}", work.display(), e))?;
        Ok(EngineOracle {
            patcher: Arc::new(prepared.patcher),
            server: server.to_path_buf(),
            map: map.to_path_buf(),
            dir: work.to_path_buf(),
            seq: AtomicU64::new(0),
            calls: AtomicU64::new(0),
            prefix_ticks: AtomicU64::new(0),
            generated: prepared.generated,
            container_path: prepared.path,
        })
    }

    /// The generated baseline used to sanitize the complete input archive.
    pub fn generated_inputs(&self) -> Inputs {
        self.generated.inputs().clone()
    }

    pub fn container_path(&self) -> &Path {
        &self.container_path
    }

    /// How many ticks a tape may have. The container's archive length.
    pub fn capacity(&self) -> usize {
        self.patcher.n()
    }

    /// Lay a search tape into the container's tick frame.
    ///
    /// # The search's tick 0 is NOT the file's tick 0
    ///
    /// The fork server consumes the generated baseline below its boundary; a
    /// write there would be a silent no-op. So the search's tick 0 is the
    /// BOUNDARY, and writing its tape at file tick 0 produces a different run
    /// from the one the fork evaluated.
    ///
    /// Measured: the fork reported a tape reaching station 55 with one gate
    /// collected, and the plain oracle called the written file `Dnf cps 0`.
    /// That reads exactly like the phantom pattern and it was an alignment
    /// bug — which is why the first question to ask of a disagreement is
    /// whether the two instruments were given the same run.
    ///
    /// Ticks past the end of the candidate keep the generated baseline rather
    /// than going neutral: a neutral pad lifts the throttle before the line on
    /// any tape whose length was underestimated.
    fn to_inputs(&self, tape: &[Input]) -> forkoracle::inputs::Inputs {
        let n = self.patcher.n();
        let base = self.generated.inputs();
        let mut steer = base.steer.clone();
        let mut gas = base.gas.clone();
        let mut brake = base.brake.clone();
        steer.resize(n, 0);
        gas.resize(n, false);
        brake.resize(n, false);
        let off = self.prefix_ticks.load(Ordering::Relaxed) as usize;
        for (i, t) in tape.iter().enumerate() {
            let j = off + i;
            if j >= n {
                break;
            }
            steer[j] = t.steer;
            gas[j] = t.gas;
            brake[j] = t.brake;
        }
        forkoracle::inputs::Inputs { steer, gas, brake }
    }

    /// Where the search's tick 0 lands in the file: the fork server's own
    /// probed boundary.
    pub fn set_prefix_ticks(&self, n: u64) -> Result<(), String> {
        self.patcher.check_window(n as usize, self.patcher.n())?;
        self.prefix_ticks.store(n, Ordering::Relaxed);
        Ok(())
    }
    pub fn prefix_ticks(&self) -> u64 {
        self.prefix_ticks.load(Ordering::Relaxed)
    }

    /// Write a self-contained candidate file using the same generated prefix and
    /// tick frame the fork workers used.
    pub fn write_candidate(&self, tape: &[Input], out: &Path) -> Result<(), String> {
        let off = self.prefix_ticks.load(Ordering::Relaxed) as usize;
        if tape.len() + off > self.patcher.n() {
            return Err(format!(
                "candidate has {} ticks after prefix {}, beyond container capacity {}",
                tape.len(),
                off,
                self.patcher.n()
            ));
        }
        let mut buf = self.patcher.base.clone();
        self.patcher.apply(&mut buf, &self.to_inputs(tape));
        std::fs::write(out, buf).map_err(|e| format!("{}: {}", out.display(), e))
    }

    /// Confirm one tape and also return **the engine's own echo of the input
    /// tape it decoded**.
    ///
    /// This is the control that matters at startup and it costs nothing. Two
    /// tapes that differ in every tick must produce different echoes; if they
    /// do not, the writer is not reaching the engine and every number after
    /// that is about a run nobody wrote. Comparing verdicts cannot do this
    /// job — two tapes that both crash at the first corner both return
    /// `Dnf cps 0`, which is a true statement about the driving and no
    /// statement at all about the plumbing.
    pub fn confirm_echo(
        &self,
        tape: &[Input],
    ) -> Result<(Verdict, String, String, String), String> {
        let batch = self.seq.fetch_add(1, Ordering::Relaxed);
        let mut buf = self.patcher.base.clone();
        self.patcher.apply(&mut buf, &self.to_inputs(tape));
        let p = self.dir.join(format!("echo_{}.Ghost.Gbx", batch));
        std::fs::write(&p, &buf).map_err(|e| format!("{}: {}", p.display(), e))?;
        let res = validate_many(
            &self.server,
            &[p.as_path()],
            MapsMode::One(&self.map),
            "tmexplore-echo",
        )?;
        let _ = std::fs::remove_file(&p);
        let r = res.first().ok_or("the server mentioned no file")?;
        Ok((
            crate::verdict_of(r)?,
            r.inputs.clone(),
            r.map_uid.clone(),
            r.desc.clone(),
        ))
    }

    /// Confirm a batch in one server launch.
    ///
    /// One launch dominates the per-file cost, so a batch of thirty costs
    /// about what one does. The explorer confirms one candidate at a time
    /// today because candidates are rare; this exists for the campaign sweep.
    pub fn confirm_many(&self, tapes: &[Vec<Input>]) -> Result<Vec<Verdict>, String> {
        if tapes.is_empty() {
            return Ok(Vec::new());
        }
        let off = self.prefix_ticks.load(Ordering::Relaxed) as usize;
        if tapes.iter().any(|t| t.len() + off > self.patcher.n()) {
            return Err(format!(
                "a tape is longer than the container's input archive ({} ticks). \
                 A longer tape is a different run, and truncating it silently would be a result \
                 about a run nobody asked for.",
                self.patcher.n()
            ));
        }
        let batch = self.seq.fetch_add(1, Ordering::Relaxed);
        let mut buf = self.patcher.base.clone();
        let mut files: Vec<PathBuf> = Vec::with_capacity(tapes.len());
        for (i, t) in tapes.iter().enumerate() {
            self.patcher.apply(&mut buf, &self.to_inputs(t));
            let p = self.dir.join(format!("cand_{}_{:04}.Ghost.Gbx", batch, i));
            std::fs::write(&p, &buf).map_err(|e| format!("{}: {}", p.display(), e))?;
            files.push(p);
        }
        let refs: Vec<&Path> = files.iter().map(|p| p.as_path()).collect();
        let res = validate_many(&self.server, &refs, MapsMode::One(&self.map), "tmexplore")?;
        self.calls.fetch_add(tapes.len() as u64, Ordering::Relaxed);

        // Match answers back to files BY NAME. The server reports in the order
        // it read them, which is not the order they were written, and a
        // positional match silently attributes one run's time to another.
        let mut out = Vec::with_capacity(tapes.len());
        for f in &files {
            let want = f.file_name().unwrap().to_string_lossy().to_string();
            match res.iter().find(|r| r.file.ends_with(&want)) {
                Some(r) => out.push(crate::verdict_of(r)?),
                // A file the server never mentioned is a fact worth having,
                // not a silent DNF: an absent row is not a failure row.
                None => {
                    return Err(format!("the server never mentioned {}", want));
                }
            }
        }
        for f in &files {
            let _ = std::fs::remove_file(f);
        }
        Ok(out)
    }
}

impl PlainOracle for EngineOracle {
    fn confirm(&self, tape: &[Input]) -> Result<Verdict, String> {
        Ok(self.confirm_many(&[tape.to_vec()])?[0])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const FIXTURE: &str = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/human_23013.Ghost.Gbx"
    );

    #[test]
    fn opaque_container_exposes_only_generated_inputs() {
        let original = Tape::from_file(FIXTURE).unwrap();
        let template = ContainerTemplate::load(Path::new(FIXTURE)).unwrap();
        let generated = GeneratedTape::plumbing(template.capacity());
        let expected = generated.inputs().clone();
        let out = std::env::temp_dir().join(format!(
            "tmexplore-opaque-container-{}.Ghost.Gbx",
            std::process::id()
        ));
        let prepared = template.prepare(generated, &out).unwrap();
        let back = Tape::from_file(&out.to_string_lossy()).unwrap();

        assert_eq!(back.steer_i8s(), expected.steer);
        assert_eq!(
            back.accels(),
            expected
                .gas
                .iter()
                .map(|v| u8::from(*v))
                .collect::<Vec<_>>()
        );
        assert_eq!(
            back.brakes(),
            expected
                .brake
                .iter()
                .map(|v| u8::from(*v))
                .collect::<Vec<_>>()
        );
        assert_eq!(
            back.archives[0]
                .packets
                .iter()
                .map(|p| p.mode)
                .collect::<Vec<_>>(),
            original.archives[0]
                .packets
                .iter()
                .map(|p| p.mode)
                .collect::<Vec<_>>()
        );
        assert!(back.archives[0]
            .packets
            .iter()
            .all(|p| p.mouse.is_none() && !p.respawn()));
        assert_eq!(prepared.path(), out.as_path());
        let _ = std::fs::remove_file(out);
    }
}
