//! Shared fixture paths for every test in this crate.
//!
//! The fixtures are CHECKED IN, under `tools/testdata`, and resolved at compile
//! time from this crate's own manifest directory. Two reasons, both learned:
//!
//! 1. **A test that skips when its fixture is missing is a test that passes
//!    when it tests nothing.** `golden_full_fields` used to look for
//!    `/tmp/entrec_full`, print `SKIP` and return `ok` — and the directory could
//!    only be regenerated by running the Python this crate exists to replace,
//!    which is not on any box any more. It had been green and vacuous for as
//!    long as it had existed. Everything here is either present or a failure.
//!
//! 2. **Searching for a fixture relative to the cwd gives a different answer
//!    depending on where you stand.** `ghost selftest` had a three-rung ladder
//!    whose last rung named a tree that no longer exists, so running it from
//!    anywhere but one directory failed on every fixture with "No such file or
//!    directory" instead of saying the path was wrong.

#![allow(dead_code)]

use std::path::{Path, PathBuf};

/// `tools/testdata` — one corpus, shared by `gbx`, `tmtraj`, `ghost` and
/// `tmsite`, rather than one per tool.
pub const TESTDATA: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../testdata");

/// The 45 ghosts, and the CSV / path-JSON / report artefacts the retired
/// Python (`entrec.py`, `decode_all.py`, `cluster_lines.py`, `lines.py`)
/// produced from them. This is the ground truth for the decoder port and it is
/// unreproducible: the Python is gone. It lives in git for that reason.
pub fn goldens() -> PathBuf {
    let p = PathBuf::from(TESTDATA).join("decoder-goldens");
    assert!(
        p.is_dir(),
        "checked-in fixture directory missing: {}\n\
         This is not a reason to skip: the tests below have nothing to test without it.",
        p.display()
    );
    p
}

pub fn fixture(name: &str) -> PathBuf {
    let p = PathBuf::from(TESTDATA).join(name);
    assert!(p.is_file(), "checked-in fixture missing: {}", p.display());
    p
}

/// Every reference run, by name, with the ghost that produced it.
pub fn runs() -> Vec<(String, PathBuf)> {
    let g = goldens();
    let mut v: Vec<(String, PathBuf)> = std::fs::read_dir(g.join("paths"))
        .expect("paths/")
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .filter(|n| n.ends_with(".json"))
        .map(|n| n.trim_end_matches(".json").to_string())
        .filter_map(|n| {
            let p = g.join("ghosts").join(format!("{}.Ghost.Gbx", n));
            p.is_file().then_some((n, p))
        })
        .collect();
    v.sort();
    v
}

pub fn read(p: &Path) -> String {
    std::fs::read_to_string(p).unwrap_or_else(|e| panic!("{}: {}", p.display(), e))
}
