//! All 48 decoded fields, pinned — not just the 29 the CSV writes.
//!
//! ## What this used to be, and why it was worthless
//!
//! It compared against `entrec.py GHOST --json`, regenerated by hand into
//! `/tmp/entrec_full`. That directory is not checked in and cannot be
//! recreated: the Python it needs is the Python this crate replaced, and it is
//! not on any box any more. The test's response to a missing fixture was
//!
//! ```text
//! if !Path::new(FULL).is_dir() { println!("SKIP: ..."); return; }
//! ```
//!
//! so it had been green, and testing precisely nothing, for its whole life. A
//! test that passes when its fixture is absent is worse than no test: it
//! occupies the slot where a real one would go.
//!
//! ## What it is now, and what it does and does not prove
//!
//! Every field of every sample of the checked-in reference runs, rendered by
//! `serial::full_json_string` and pinned by MD5 against a digest list committed
//! beside the fixtures. (A digest, not the JSON: the rendered text is 20 MB and
//! a hash pins it exactly as well.)
//!
//! * It **does** prove the other 19 fields cannot change without somebody
//!   noticing — the CSV goldens cover 29 of the 48, and the remaining 19 (all
//!   four ice, all four dirt, `wetness`, `sim_time_coef`, the raw mode bytes,
//!   the wheel rotations, `is_top_contact`) had no coverage at all.
//! * It does **not** prove they are CORRECT. It is a behaviour lock against an
//!   implementation, not a measurement against the world. Correctness for the
//!   29 CSV columns is `golden_decode.rs`, which compares against artefacts a
//!   different implementation produced; correctness for the 19 is what
//!   `tmtraj fields` labels DERIVED and GUESS, and those labels are the honest
//!   statement of what is known.
//!
//! Regenerate deliberately, never casually:
//! `TMTRAJ_BLESS=1 cargo test --release --test golden_full_fields`.

mod common;

use gbx::record;
use tmtraj::testonly::md5_hex;
use tmtraj::testonly as serial;

#[test]
fn every_decoded_field_is_pinned() {
    let digests = common::goldens().join("full-json.md5");
    let bless = std::env::var("TMTRAJ_BLESS").is_ok();
    let runs = common::runs();
    assert!(
        runs.len() >= 40,
        "expected the checked-in reference corpus, found {} runs",
        runs.len()
    );
    let mut mine = String::new();
    let mut samples = 0usize;
    for (name, path) in &runs {
        let dec = record::decode_ghost(path.to_str().unwrap())
            .unwrap_or_else(|e| panic!("{}: {}", name, e));
        samples += dec.samples.len();
        // Hash the RENDERED text with the absolute path masked: the JSON
        // carries the file's own path, so an unmasked digest pins the
        // directory the tests were blessed in and fails in a fresh clone.
        let text = serial::full_json_string(&dec)
            .replace(path.to_str().unwrap(), "$FIXTURE");
        mine.push_str(&format!("{}  {}\n", md5_hex(text.as_bytes()), name));
    }
    if bless {
        std::fs::write(&digests, &mine).unwrap();
        println!("blessed {} digests -> {}", runs.len(), digests.display());
        return;
    }
    let gold = std::fs::read_to_string(&digests).unwrap_or_else(|e| {
        panic!(
            "{}: {} -- run TMTRAJ_BLESS=1 cargo test --test golden_full_fields to create it",
            digests.display(),
            e
        )
    });
    // Report every run that moved, not just the first.
    let bad: Vec<(&str, &str)> = mine
        .lines()
        .zip(gold.lines())
        .filter(|(a, b)| a != b)
        .map(|(a, b)| (a, b))
        .collect();
    assert!(
        bad.is_empty(),
        "{} of {} runs render differently:\n  now  {}\n  was  {}",
        bad.len(),
        runs.len(),
        bad.iter().map(|(a, _)| *a).collect::<Vec<_>>().join("\n  now  "),
        bad.iter().map(|(_, b)| *b).collect::<Vec<_>>().join("\n  was  ")
    );
    assert_eq!(mine.lines().count(), gold.lines().count(), "the corpus changed size");
    println!(
        "{} runs, {} samples, {} fields per sample -- all pinned",
        runs.len(),
        samples,
        record::FIELD_CONFIDENCE.len()
    );
}

/// The field table and the accessor cannot drift apart, and the tier counts are
/// the documented ones. `tmtraj fields` IS the documentation of what this
/// project believes about the format, so a silent change to it is a silent
/// change to a published claim.
#[test]
fn the_field_table_is_the_documented_one() {
    use tmtraj::testonly::SampleFields;
    let s = record::Sample::default();
    for f in record::FIELD_CONFIDENCE {
        let _ = s.field(f.name);
    }
    for c in serial::CSV_COLUMNS {
        assert!(
            record::FIELD_CONFIDENCE.iter().any(|f| f.name == *c),
            "CSV column {} is not in the field table",
            c
        );
    }
    let n = |c: record::Conf| record::FIELD_CONFIDENCE.iter().filter(|f| f.conf == c).count();
    assert_eq!(
        (
            record::FIELD_CONFIDENCE.len(),
            n(record::Conf::Verified),
            n(record::Conf::Derived),
            n(record::Conf::Guess)
        ),
        (48, 18, 18, 12),
        "the VERIFIED / DERIVED / GUESS split changed. That is a change to what this project \
         CLAIMS to know about the format, and it needs a measurement behind it, not a build."
    );
}
