//! `autopilot/STATUS.md` — the one file to open after a week away.
//!
//! Written for a person. Three rules keep it from rotting, which is the way
//! status pages normally die:
//!
//! 1. **Every number is rendered from state at generation time.** Nothing is
//!    typed in, so nothing can be true-then-stale.
//! 2. **Freshness is computed and stated.** If the newest sample is old, the
//!    page says the run is not reporting — it never presents an old rate as if
//!    it were current. A page that shows yesterday's throughput next to
//!    today's date is worse than no page.
//! 3. **Times are seconds with a decimal, maps are named.** The project's
//!    presentation rules, applied here so a reader never has to translate.

use crate::alarms::{self, Severity};
use crate::budget;
use crate::config::Job;
use crate::lease;
use crate::ledger;
use crate::paths::Layout;
use crate::state;
use crate::time::{dur, iso};

/// Render the page from state. `credential` is passed in rather than read,
/// for the same reason `reconstruct` does not read it: a renderer whose
/// output depends on the machine it runs on cannot be tested.
pub fn render_with(
    l: &Layout,
    job: &Job,
    now: i64,
    credential: Option<crate::credential::Health>,
) -> Result<String, String> {
    render_inner(l, job, now, credential, false)
}

/// The page as this box sees it, credential included.
pub fn render_here(l: &Layout, job: &Job, now: i64) -> Result<String, String> {
    let home = std::env::var("HOME").unwrap_or_default();
    render_inner(l, job, now, Some(crate::credential::health(&home)), true)
}

/// Test-facing: no claim about any machine's credential.
#[cfg(test)]
pub fn render(l: &Layout, job: &Job, now: i64) -> Result<String, String> {
    render_inner(l, job, now, None, false)
}

/// Collapse a value into one line for a markdown table cell.
///
/// A bank receipt can carry a multi-line error body from a failing bridge.
/// Pasted raw into a `|` table it breaks the table, and the page a human reads
/// stops rendering exactly when something has gone wrong — the one moment it
/// has to be readable.
fn one_line(s: &str, max: usize) -> String {
    let mut out = String::new();
    let mut last_space = false;
    for c in s.chars() {
        let c = if c == '\n' || c == '\r' || c == '\t' || c == '|' { ' ' } else { c };
        if c == ' ' {
            if !last_space && !out.is_empty() {
                out.push(' ');
            }
            last_space = true;
        } else {
            out.push(c);
            last_space = false;
        }
    }
    let out = out.trim_end().to_string();
    if out.chars().count() > max {
        let cut: String = out.chars().take(max).collect();
        format!("{cut}…")
    } else {
        out
    }
}

fn render_inner(
    l: &Layout,
    job: &Job,
    now: i64,
    credential: Option<crate::credential::Health>,
    this_box: bool,
) -> Result<String, String> {
    let r = state::reconstruct(l, now)?;
    // The alarms table and the "GitHub banking" row must be two views of ONE
    // judgement. Before 2026-08-26 the row consulted the credential and the
    // table did not, so a page could say **DEGRADED** at the top and "None
    // firing" six lines below — the reader's only summary, disagreeing with
    // itself about whether anything was wrong.
    let mut v = r.view.clone();
    if let Some(h) = &credential {
        v.credential = Some(h.ok());
        v.credential_present = Some(!matches!(
            h,
            crate::credential::Health::Absent | crate::credential::Health::Unsafe(_)
        ));
    }
    if this_box {
        v.supervisor_here = Some(crate::beat::watch_pid().is_some());
        v.this_node = Some(crate::paths::node_id());
    }
    let v = &v;
    let fired = alarms::evaluate(v, &job.alarms);
    let counters = budget::total_for(&l.budget_dir(), Some(&job.budget_key))?;
    let boxes = lease::all(l)?;
    let entries = ledger::all(l)?;

    let newest_sample = v.samples.last().map(|s| s.ts);
    let sample_age = newest_sample.map(|t| now - t);
    let reporting = sample_age.map(|a| a <= job.sample_s * 4).unwrap_or(false);

    let mut s = String::new();

    s.push_str("# TM2020 autopilot — status\n\n");
    s.push_str(&format!(
        "*Generated by `tmhaul status` at {}. Every number below is read out of\n`autopilot/state/` at generation time; nothing here is typed in by hand.*\n\n",
        iso(now)
    ));

    // ---- the headline: is anything actually happening?
    s.push_str("## Right now\n\n");
    let headline = if !v.run_active {
        "**Nothing is running.** No run is marked active in the journal.".to_string()
    } else if r.run_started.map(|t| now - t < job.alarms.zero_window_s).unwrap_or(false)
        && !v.samples.iter().any(|s| Some(s.ts) > r.run_started)
    {
        // A run that has only just started has not had a chance to say
        // anything. Saying "not reporting" here would put a scary sentence at
        // the top of the page after every routine restart.
        format!(
            "**Just started**, {} ago, and has not reported yet.",
            dur(now - r.run_started.unwrap_or(now))
        )
    } else if !reporting {
        format!(
            "**A run is marked active but it is not reporting.** Last progress sample {}{}.",
            sample_age.map(|a| format!("{} ago", dur(a))).unwrap_or_else(|| "never".into()),
            newest_sample.map(|t| format!(" (at {})", iso(t))).unwrap_or_default()
        )
    } else {
        match state::recent_rate(v, job.alarms.collapse_recent_s) {
            Some(rate) => format!(
                "**Running.** {rate:.1} evals/s over the last {}.",
                dur(job.alarms.collapse_recent_s)
            ),
            // Never print `0.0 evals/s` for "not enough samples to divide by".
            // A zero that means "unmeasured" is the exact shape of the bug
            // this project keeps paying for.
            None => format!(
                "**Running**, and too new to have a rate yet — {} sample(s) so far.",
                v.samples.len()
            ),
        }
    };
    s.push_str(&headline);
    s.push_str("\n\n");

    s.push_str(&format!("| | |\n|---|---|\n"));
    s.push_str(&format!("| map | **{}** |\n", job.map_name));
    s.push_str(&format!("| rung | {} |\n", job.rung));
    s.push_str(&format!("| objective | {} |\n", job.objective));
    s.push_str(&format!(
        "| best objective ever seen | {} |\n",
        state::best_objective(v).map(|b| format!("{b}")).unwrap_or_else(|| "none reported yet".into())
    ));
    s.push_str(&format!(
        "| run started | {} |\n",
        r.run_started.map(|t| format!("{} ({} ago)", iso(t), dur(now - t))).unwrap_or_else(|| "—".into())
    ));
    s.push_str(&format!(
        "| GitHub banking | {} |\n",
        match &credential {
            None => "not checked on this pass".to_string(),
            Some(h) if h.ok() => "working".to_string(),
            Some(h) => format!("**DEGRADED** — {}", h.describe()),
        }
    ));
    s.push_str(&format!(
        "| last banked | {} |\n",
        v.last_bank
            .map(|t| format!(
                "{} ago — {}",
                dur(now - t),
                one_line(&r.last_bank_receipt.clone().unwrap_or_default(), 240)
            ))
            .unwrap_or_else(|| "**never**".into())
    ));
    // Only when there is something to say. On a healthy day GitHub is level
    // and a row reading "0 commits at risk" is one more line to scroll past.
    if this_box {
        if let Ok(Some(n)) = crate::codemirror::unpushed_code(l, &job.branch) {
            if n > 0 {
                let mirrored = crate::log::read_all(&l.journal_dir())
                    .ok()
                    .zip(crate::codemirror::content_key(&l.repo).ok())
                    .map(|(recs, key)| {
                        recs.iter()
                            .any(|x| x.kind == "code_mirror" && x.get("key") == Some(key.as_str()))
                    })
                    .unwrap_or(false);
                s.push_str(&format!(
                    "| commits GitHub has not got | {n} — {} |\n",
                    if mirrored {
                        "mirrored to a paste; a fresh box picks them up with `tmhaul code recover`"
                    } else {
                        "**not mirrored** — they exist only on this box; run `tmhaul code mirror`"
                    }
                ));
            }
        }
    }
    s.push('\n');

    // ---- alarms
    s.push_str("## Alarms\n\n");
    if fired.is_empty() {
        s.push_str("None firing.\n\nThat sentence is only worth reading because every alarm has a test that\nmakes it fire: `cd tools/haul && cargo test`, or `tmhaul alarms selftest` to\nwatch each one fire on this box right now.\n\n");
    } else {
        s.push_str("| alarm | severity | detail |\n|---|---|---|\n");
        for f in &fired {
            s.push_str(&format!(
                "| `{}` | {} | {} |\n",
                f.id,
                match f.severity {
                    Severity::Critical => "**critical**",
                    Severity::Warn => "warn",
                },
                f.detail
            ));
        }
        s.push('\n');
    }

    // ---- budget
    s.push_str("## Budget — work done, not time passed\n\n");
    if job.budget.has_switch {
        s.push_str(&format!(
            "The pre-committed switch condition is **{} evals or {} of productive time**,\nafter which a learned ordering over archive bins gets added (DESIGN.md §3.2).\n\n",
            counters_thousands(job.budget.switch_evals),
            dur(job.budget.switch_productive_s)
        ));
    } else {
        s.push_str(&format!(
            "This budget (`{}`) is a **meter, not a countdown**: it has no switch condition.\nThe pre-committed 8M-eval / 10-hour switch belongs to the archive search\n(DESIGN.md §3.2), and a job that is not that search must not measure itself\nagainst it.\n\n",
            job.budget_key
        ));
    }
    s.push_str("| | |\n|---|---|\n");
    s.push_str(&format!("| evals | {} |\n", counters_thousands(counters.evals)));
    s.push_str(&format!(
        "| productive time | {}{} |\n",
        dur(counters.productive_s),
        if job.budget.has_switch { format!(" of {}", dur(job.budget.switch_productive_s)) } else { String::new() }
    ));
    s.push_str(&format!(
        "| stalled time (does **not** spend the budget) | {} |\n",
        dur(counters.stalled_s)
    ));
    if job.budget.has_switch {
        s.push_str(&format!("| spent | {:.1}% |\n", 100.0 * counters.spent_fraction(&job.budget)));
        s.push_str(&format!(
            "| switch reached | {} |\n\n",
            if counters.switch_reached(&job.budget) { "**yes**" } else { "no" }
        ));
    } else {
        s.push_str("| switch | none for this budget |\n\n");
    }

    // ---- queue
    s.push_str("## Queue\n\n");
    s.push_str(&format!(
        "{} pending · {} claimed ({} expired) · {} completed{}\n\n",
        v.queue.pending,
        v.queue.claimed,
        v.queue.expired_claims,
        state::reconstruct(l, now)?.view.queue.pending.saturating_mul(0)
            + crate::queue::Queue::open(l).map_err(|e| e.to_string())?.done()?.len(),
        v.queue
            .last_completion
            .map(|t| format!(", last {} ago", dur(now - t)))
            .unwrap_or_default()
    ));

    // ---- boxes
    s.push_str("## Boxes\n\n");
    if boxes.is_empty() {
        s.push_str("None registered.\n\n");
    } else {
        s.push_str("| box | state | lease | last seen |\n|---|---|---|---|\n");
        for b in &boxes {
            s.push_str(&format!(
                "| `{}` | {} | {} | {} ago |\n",
                b.node,
                if b.retired { "retired" } else { "**active**" },
                b.lease_expires
                    .map(|e| format!("{} ({})", iso(e), if e > now { format!("{} left", dur(e - now)) } else { "expired".into() }))
                    .unwrap_or_else(|| "not declared".into()),
                dur(now - b.last_seen)
            ));
        }
        s.push('\n');
    }

    // ---- what changed
    s.push_str("## What has been tried\n\n");
    if entries.is_empty() {
        s.push_str("Nothing recorded yet. `tmhaul ledger add` is how a configuration and its\nreasoning get written down; the artifact alone is not worth much in three\nmonths.\n\n");
    } else {
        s.push_str("Newest first. The `why` is the part that will still be worth reading later.\n\n");
        for e in entries.iter().rev().take(15) {
            s.push_str(&format!(
                "**{}** — {} · *{}*\n\n- config: `{}`\n- produced: {}\n- why: {}\n{}\n",
                iso(e.ts),
                e.what,
                e.claim.as_str(),
                e.config,
                e.produced,
                e.why.replace('\n', "\n  "),
                if e.control.is_empty() {
                    String::new()
                } else {
                    format!("- control: {}\n", e.control)
                }
            ));
        }
    }

    // ---- recent journal
    s.push_str("## Recent events\n\n");
    let notable: Vec<_> = r
        .journal
        .iter()
        .filter(|x| x.kind != "sample")
        .rev()
        .take(25)
        .collect();
    if notable.is_empty() {
        s.push_str("Nothing yet.\n\n");
    } else {
        s.push_str("```\n");
        for rec in notable.iter().rev() {
            s.push_str(&rec.render());
            s.push('\n');
        }
        s.push_str("```\n\n");
    }

    s.push_str("---\n\n");
    s.push_str("*Operating this thing: `autopilot/HARNESS.md`. Failures we have already paid\nfor and their fixes: `autopilot/OPS-LOG.md`.*\n");

    Ok(s)
}

fn counters_thousands(n: u64) -> String {
    let s = n.to_string();
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if i > 0 && (s.len() - i) % 3 == 0 {
            out.push(',');
        }
        out.push(c);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::log::Log;
    use crate::rec::Rec;

    fn layout(name: &str) -> Layout {
        let p = std::env::temp_dir().join(format!("haul-status-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&p);
        for d in Layout::new(&p).all_dirs() {
            std::fs::create_dir_all(d).unwrap();
        }
        Layout::new(p)
    }

    #[test]
    fn an_empty_project_renders_without_pretending_anything_is_running() {
        let l = layout("empty");
        let page = render(&l, &Job::default(), 1_800_000_000).unwrap();
        assert!(page.contains("Nothing is running"));
        assert!(!page.contains("evals/s over the last"));
    }

    #[test]
    fn a_stale_sample_is_never_presented_as_a_current_rate() {
        // The anti-rot property, and the one that matters most after a week
        // away: an old number must not appear next to today's date as if it
        // were now.
        let l = layout("stale");
        let log = Log::shard(&l.journal_dir(), "boxA", 1).unwrap();
        let now = 1_800_000_000;
        log.append(&Rec::at(now - 86_400, "run_start")).unwrap();
        for i in 0..10 {
            log.append(
                &Rec::at(now - 86_400 + i * 60, "sample")
                    .f("evals", i as u64 * 600)
                    .f("best", 25)
                    .f("worker_alive", 1),
            )
            .unwrap();
        }
        let page = render(&l, &Job::default(), now).unwrap();
        assert!(page.contains("not reporting"), "{page}");
        assert!(page.contains("zero_throughput"), "and the alarm must be on the page too");
    }

    #[test]
    fn a_healthy_run_shows_its_rate_and_no_alarms() {
        let l = layout("healthy");
        let log = Log::shard(&l.journal_dir(), "boxA", 1).unwrap();
        let now = 1_800_000_000;
        // A real worker reports where its car started; the harness alarms if it
        // does not, so the fixture for a HEALTHY run has to carry one too.
        log.append(&Rec::at(now - 7200, "run_start").f("start_dev_m", 0.9)).unwrap();
        for i in 0..=120 {
            log.append(
                &Rec::at(now - 7200 + i * 60, "sample")
                    .f("evals", i as u64 * 600)
                    .f("best", 20 + i)
                    .f("disk_free_mb", 200_000)
                    .f("worker_alive", 1),
            )
            .unwrap();
        }
        log.append(&Rec::at(now - 300, "bank").f("receipt", "commit deadbeef · mirror P1")).unwrap();
        crate::lease::register_at(&l, "boxA", now - 60, Some(now + 3600), "test").unwrap();
        crate::budget::record(&l.budget_dir(), "boxA", "archive-search", 72_000, 7200).unwrap();

        let page = render(&l, &Job::default(), now).unwrap();
        assert!(page.contains("**Running.**"), "{page}");
        assert!(page.contains("10.0 evals/s"), "{page}");
        assert!(page.contains("None firing"), "{page}");
        assert!(page.contains("72,000"), "the eval count must be readable: {page}");
        assert!(page.contains("2h 0m of 10h 0m"), "{page}");
    }

    #[test]
    fn a_brand_new_run_says_so_rather_than_printing_zero_evals_per_second() {
        // One sample cannot yield a rate. Printing `0.0 evals/s` for that
        // would be a number that looks measured and is not — and it would sit
        // right next to the word Running, which is the worst place for it.
        let l = layout("newborn");
        let log = Log::shard(&l.journal_dir(), "boxA", 1).unwrap();
        let now = 1_800_000_000;
        log.append(&Rec::at(now - 30, "run_start")).unwrap();
        log.append(&Rec::at(now - 30, "sample").f("evals", 12).f("worker_alive", 1)).unwrap();
        let page = render(&l, &Job::default(), now).unwrap();
        assert!(
            page.contains("too new to have a rate") || page.contains("Just started"),
            "{page}"
        );
        assert!(!page.contains("0.0 evals/s"), "{page}");
    }

    #[test]
    fn a_degraded_bridge_appears_in_the_alarms_table_not_only_in_the_banking_row() {
        // The defect this pins down, seen for real on 2026-08-26: the page said
        // "GitHub banking: **DEGRADED**" in the summary table and "None firing"
        // in the alarms section of the same render. The two came from different
        // views of the world — the row consulted the credential, the alarm
        // evaluation did not — so the page contradicted itself about whether
        // anything was wrong, and the alarms section, which is where a reader
        // looks, said no.
        let l = layout("degraded-bridge");
        let log = Log::shard(&l.journal_dir(), "boxA", 1).unwrap();
        let now = 1_800_000_000;
        log.append(&Rec::at(now - 7200, "run_start").f("start_dev_m", 0.9)).unwrap();
        for i in 0..=120 {
            log.append(
                &Rec::at(now - 7200 + i * 60, "sample")
                    .f("evals", i as u64 * 600)
                    .f("best", 20 + i)
                    .f("disk_free_mb", 200_000)
                    .f("worker_alive", 1),
            )
            .unwrap();
        }
        log.append(&Rec::at(now - 300, "bank").f("receipt", "commit deadbeef · mirror P1")).unwrap();
        crate::lease::register_at(&l, "boxA", now - 60, Some(now + 3600), "test").unwrap();

        let down = crate::credential::Health::BridgeDown("the probe was sent and the bridge did not answer it");
        let page = render_with(&l, &Job::default(), now, Some(down)).unwrap();
        assert!(page.contains("**DEGRADED**"), "{page}");
        assert!(page.contains("banking_degraded"), "the alarm must be on the page: {page}");
        assert!(!page.contains("None firing"), "the page must not contradict itself: {page}");

        // Control: the same page with a working bridge says neither thing.
        let page_ok = render_with(&l, &Job::default(), now, Some(crate::credential::Health::Working)).unwrap();
        assert!(page_ok.contains("None firing"), "{page_ok}");
        assert!(!page_ok.contains("**DEGRADED**"), "{page_ok}");
    }

    #[test]
    fn a_multi_line_bank_receipt_cannot_break_the_table() {
        // A failing bridge writes a retry transcript into the receipt. Rendered
        // raw into a `|` table it breaks the page exactly when the page matters.
        let l = layout("ugly-receipt");
        let log = Log::shard(&l.journal_dir(), "boxA", 1).unwrap();
        let now = 1_800_000_000;
        log.append(&Rec::at(now - 300, "sample").f("evals", 10).f("worker_alive", 1)).unwrap();
        log.append(
            &Rec::at(now - 300, "bank")
                .f("receipt", "commit abc · PUSH FAILED: wsx: retrying\n  stderr: offline\nwsx: gave | up"),
        )
        .unwrap();
        let page = render(&l, &Job::default(), now).unwrap();
        let row = page
            .lines()
            .find(|l| l.starts_with("| last banked |"))
            .expect("the row must exist");
        assert!(row.ends_with(" |"), "the row must be one closed table cell: {row}");
        assert!(!row.contains("stderr: offline |"), "no stray pipe from the body: {row}");
        assert!(row.contains("PUSH FAILED"), "and it must still say what happened: {row}");
    }

    #[test]
    fn one_line_collapses_and_caps() {
        assert_eq!(one_line("a\nb\tc", 80), "a b c");
        assert_eq!(one_line("a   b", 80), "a b");
        assert_eq!(one_line("a|b", 80), "a b");
        assert_eq!(one_line("abcdef", 3), "abc…");
    }

    #[test]
    fn thousands_separators_are_right() {
        assert_eq!(counters_thousands(0), "0");
        assert_eq!(counters_thousands(999), "999");
        assert_eq!(counters_thousands(1_000), "1,000");
        assert_eq!(counters_thousands(8_000_000), "8,000,000");
    }
}
