string last="";
string lastProbe="";
string V3(const vec3 &in v){return Text::Format("%.2f",v.x)+","+Text::Format("%.2f",v.y)+","+Text::Format("%.2f",v.z);}
void Probe(CGameCtnEditorFree@ ed){auto ch=ed.Challenge;IO::File f(IO::FromDataFolder("probe-out.tsv"),IO::FileMode::Write);f.Write("copper\t"+ch.CopperPrice+"\n");f.Write("kind\tindex\tmodel\tauthor\tpos\tscale\tmodel_loaded\tentity_model\n");for(uint i=0;i<ch.AnchoredObjects.Length;i++){auto o=ch.AnchoredObjects[i];string em="null";string loaded="0";if(o.ItemModel!is null){loaded="1";if(o.ItemModel.EntityModel!is null)em=Reflection::TypeOf(o.ItemModel.EntityModel).Name;}string nm="?";if(o.ItemModel!is null){nm=o.ItemModel.IdName;}f.Write("item\t"+i+"\t"+nm+"\t"+(o.ItemModel!is null?o.ItemModel.Author.GetName():"")+"\t"+V3(o.AbsolutePositionInMap)+"\t"+o.Scale+"\t"+loaded+"\t"+em+"\n");}f.Write("blocks\t"+ch.Blocks.Length+"\n");for(uint i=0;i<ch.Blocks.Length;i++){auto b=ch.Blocks[i];f.Write("block\t"+i+"\t"+b.BlockInfo.Name+"\t"+(b.IsGhostBlock()?"ghost":"")+"\t"+b.CoordX+","+b.CoordY+","+b.CoordZ+"\t"+b.Dir+"\t\t\n");}f.Close();print("PROBE "+ch.AnchoredObjects.Length+" items");}
void CarProbe(){auto app=GetApp();auto pg=app.CurrentPlayground;if(pg is null||pg.GameTerminals.Length==0)return;auto pl=cast<CSmPlayer>(pg.GameTerminals[0].ControlledPlayer);IO::File f(IO::FromDataFolder("car-out.tsv"),IO::FileMode::Write);if(pl!is null&&pl.ScriptAPI!is null){auto sa=cast<CSmScriptPlayer>(pl.ScriptAPI);f.Write("pos\t"+sa.Position.x+"\t"+sa.Position.y+"\t"+sa.Position.z+"\tspeed\t"+sa.Speed+"\n");}f.Close();print("CARPROBE");}
string lastOpen="";string lastMat="";
void DumpMaterials(CGameEditorMesh@ me){IO::File f(IO::FromDataFolder("materials-out.tsv"),IO::FileMode::Write);f.Write("count\t"+me.Material_MaterialLibGetCount()+"\tnames "+me.MaterialNames.Length+"\tids "+me.MaterialIds.Length+"\tphys "+me.MaterialPhysicsIds.Length+"\n");for(uint i=0;i<me.MaterialNames.Length;i++){string idn=i<me.MaterialIds.Length?me.MaterialIds[i].GetName():"";string ph=i<me.MaterialPhysicsIds.Length?me.MaterialPhysicsIds[i].GetName():"";f.Write(i+"\t"+me.MaterialNames[i]+"\t"+idn+"\t"+ph+"\n");}f.Close();print("MATERIALS "+me.MaterialNames.Length);}
void Main(){while(true){sleep(500);
 {string op=IO::FromDataFolder("openeditor.txt");if(IO::FileExists(op)){string s="";try{IO::File f(op,IO::FileMode::Read);s=f.ReadToEnd();f.Close();}catch{s=lastOpen;}if(s!=lastOpen){lastOpen=s;auto mp=cast<CGameManiaPlanet>(GetApp());if(mp!is null&&mp.ManiaTitleControlScriptAPI!is null){if(s.StartsWith("mesh")){mp.ManiaTitleControlScriptAPI.OpenEditor2(CGameManiaTitleControlScriptAPI::EEditorType::MeshModeler);print("OPENEDITOR mesh");}else if(s.StartsWith("item")){mp.ManiaTitleControlScriptAPI.OpenEditor2(CGameManiaTitleControlScriptAPI::EEditorType::ItemEditor);print("OPENEDITOR item");}}}}
  string mt=IO::FromDataFolder("dumpmat.txt");if(IO::FileExists(mt)){string s="";try{IO::File f(mt,IO::FileMode::Read);s=f.ReadToEnd();f.Close();}catch{s=lastMat;}if(s!=lastMat){lastMat=s;auto me=cast<CGameEditorMesh>(GetApp().Editor);if(me is null){auto ie=cast<CGameEditorItem>(GetApp().Editor);print("DUMPMAT: editor is "+(GetApp().Editor is null?"null":Reflection::TypeOf(GetApp().Editor).Name));}else{try{DumpMaterials(me);}catch{print("DUMPMAT failed: "+getExceptionInfo());}}}}}
if(GetApp().CurrentPlayground!is null&&GetApp().Editor is null){string cp=IO::FromDataFolder("carprobe.txt");if(IO::FileExists(cp)){string s="";try{IO::File f(cp,IO::FileMode::Read);s=f.ReadToEnd();f.Close();}catch{s=lastProbe;}if(s!=lastProbe){lastProbe=s;try{CarProbe();}catch{print("CARPROBE failed: "+getExceptionInfo());}}}continue;}auto ed=cast<CGameCtnEditorFree>(GetApp().Editor);if(ed is null||ed.PluginMapType is null)continue;string path=IO::FromDataFolder("cam.txt");if(IO::FileExists(path)){string s="";try{IO::File f(path,IO::FileMode::Read);s=f.ReadToEnd();f.Close();}catch{s=last;}if(s!=last){last=s;auto p=s.Split(",");if(p.Length>=6){vec3 t=vec3(Text::ParseFloat(p[0]),Text::ParseFloat(p[1]),Text::ParseFloat(p[2]));ed.PluginMapType.CameraTargetPosition=t;ed.PluginMapType.CameraToTargetDistance=Text::ParseFloat(p[3]);ed.PluginMapType.CameraHAngle=Text::ParseFloat(p[4]);ed.PluginMapType.CameraVAngle=Text::ParseFloat(p[5]);if(ed.OrbitalCameraControl!is null){ed.OrbitalCameraControl.m_TargetedPosition=t;ed.OrbitalCameraControl.m_CameraToTargetDistance=Text::ParseFloat(p[3]);ed.OrbitalCameraControl.m_CurrentHAngle=Text::ParseFloat(p[4]);ed.OrbitalCameraControl.m_CurrentVAngle=Text::ParseFloat(p[5]);}print("CAMERA "+s);}}}string pp=IO::FromDataFolder("probe.txt");if(IO::FileExists(pp)){string s="";try{IO::File f(pp,IO::FileMode::Read);s=f.ReadToEnd();f.Close();}catch{s=lastProbe;}if(s!=lastProbe){lastProbe=s;try{Probe(ed);}catch{print("PROBE failed: "+getExceptionInfo());}}}}}
