string last="";
string lastProbe="";string lastBI="";string biOut="";
string V3(const vec3 &in v){return Text::Format("%.2f",v.x)+","+Text::Format("%.2f",v.y)+","+Text::Format("%.2f",v.z);}
void Probe(CGameCtnEditorFree@ ed){auto ch=ed.Challenge;IO::File f(IO::FromDataFolder("probe-out.tsv"),IO::FileMode::Write);f.Write("copper\t"+ch.CopperPrice+"\n");f.Write("collection\t"+ch.CollectionName+"\t"+ch.DecorationName+"\t"+(ch.Collection is null?"null":ch.Collection.IdName)+"\n");f.Write("kind\tindex\tmodel\tauthor\tpos\tscale\tmodel_loaded\tentity_model\tyaw\tpitch\troll\n");for(uint i=0;i<ch.AnchoredObjects.Length;i++){auto o=ch.AnchoredObjects[i];string em="null";string loaded="0";if(o.ItemModel!is null){loaded="1";if(o.ItemModel.EntityModel!is null)em=Reflection::TypeOf(o.ItemModel.EntityModel).Name;}string nm="?";if(o.ItemModel!is null){nm=o.ItemModel.IdName;}f.Write("item\t"+i+"\t"+nm+"\t"+(o.ItemModel!is null?o.ItemModel.Author.GetName():"")+"\t"+V3(o.AbsolutePositionInMap)+"\t"+o.Scale+"\t"+loaded+"\t"+em+"\t"+Text::Format("%.4f",o.Yaw)+"\t"+Text::Format("%.4f",o.Pitch)+"\t"+Text::Format("%.4f",o.Roll)+"\n");}f.Write("blocks\t"+ch.Blocks.Length+"\n");for(uint i=0;i<ch.Blocks.Length;i++){auto b=ch.Blocks[i];f.Write("block\t"+i+"\t"+b.BlockInfo.Name+"\t"+(b.IsGhostBlock()?"ghost":"")+"\t"+b.CoordX+","+b.CoordY+","+b.CoordZ+"\t"+b.Dir+"\t\t\n");}f.Close();print("PROBE "+ch.AnchoredObjects.Length+" items");}
void CarProbe(){auto app=GetApp();auto pg=app.CurrentPlayground;if(pg is null||pg.GameTerminals.Length==0)return;auto pl=cast<CSmPlayer>(pg.GameTerminals[0].ControlledPlayer);IO::File f(IO::FromDataFolder("car-out.tsv"),IO::FileMode::Write);if(pl!is null&&pl.ScriptAPI!is null){auto sa=cast<CSmScriptPlayer>(pl.ScriptAPI);f.Write("pos\t"+sa.Position.x+"\t"+sa.Position.y+"\t"+sa.Position.z+"\tspeed\t"+sa.Speed+"\n");}f.Close();print("CARPROBE");}
string lastOpen="";string lastMat="";
void DumpMaterials(CGameEditorMesh@ me){IO::File f(IO::FromDataFolder("materials-out.tsv"),IO::FileMode::Write);f.Write("count\t"+me.Material_MaterialLibGetCount()+"\tnames "+me.MaterialNames.Length+"\tids "+me.MaterialIds.Length+"\tphys "+me.MaterialPhysicsIds.Length+"\n");for(uint i=0;i<me.MaterialNames.Length;i++){string idn=i<me.MaterialIds.Length?me.MaterialIds[i].GetName():"";string ph=i<me.MaterialPhysicsIds.Length?me.MaterialPhysicsIds[i].GetName():"";f.Write(i+"\t"+me.MaterialNames[i]+"\t"+idn+"\t"+ph+"\n");}f.Close();print("MATERIALS "+me.MaterialNames.Length);}
string FidName(CMwNod@ n){if(n is null)return "";return n.IdName;}
void DumpMobils(const string &in bname,const string &in kind,int vi,int k,const MwFastBuffer<CMwNod@> &in arr){for(uint j=0;j<arr.Length;j++){auto m=cast<CGameCtnBlockInfoMobil>(arr[j]);if(m is null){biOut+=("mobil\t"+bname+"\t"+kind+"\t"+vi+"\t"+k+"\t"+j+"\tNULL\n");continue;}biOut+=("mobil\t"+bname+"\t"+kind+"\t"+vi+"\t"+k+"\t"+j+"\t"+FidName(m.PrefabFid)+"\t"+FidName(m.SolidFid)+"\t"+V3(m.GeomTranslation)+"\t"+V3(m.GeomRotation)+"\n");}}
void DumpVariant(const string &in bname,const string &in kind,int vi,CGameCtnBlockInfoVariant@ v){if(v is null)return;biOut+=("variant\t"+bname+"\t"+kind+"\t"+vi+"\t"+v.Name+"\t"+v.Size.x+","+v.Size.y+","+v.Size.z+"\t"+v.CardinalDir+"\t"+v.SymmetricalVariantIndex+"\n");
DumpMobils(bname,kind,vi,0,v.Mobils00);DumpMobils(bname,kind,vi,1,v.Mobils01);DumpMobils(bname,kind,vi,2,v.Mobils02);DumpMobils(bname,kind,vi,3,v.Mobils03);DumpMobils(bname,kind,vi,4,v.Mobils04);DumpMobils(bname,kind,vi,5,v.Mobils05);DumpMobils(bname,kind,vi,6,v.Mobils06);DumpMobils(bname,kind,vi,7,v.Mobils07);DumpMobils(bname,kind,vi,8,v.Mobils08);DumpMobils(bname,kind,vi,9,v.Mobils09);DumpMobils(bname,kind,vi,10,v.Mobils10);DumpMobils(bname,kind,vi,11,v.Mobils11);DumpMobils(bname,kind,vi,12,v.Mobils12);DumpMobils(bname,kind,vi,13,v.Mobils13);DumpMobils(bname,kind,vi,14,v.Mobils14);DumpMobils(bname,kind,vi,15,v.Mobils15);
}
void DumpBlockInfos(CGameCtnEditorFree@ ed){auto ch=ed.Challenge;biOut="";IO::File f(IO::FromDataFolder("blockinfo-out.tsv"),IO::FileMode::Write);dictionary seen;for(uint i=0;i<ch.Blocks.Length;i++){auto b=ch.Blocks[i];if(b.BlockInfo is null)continue;string bname=b.BlockInfo.Name;f.Write("use\t"+i+"\t"+bname+"\t"+(b.IsGround?"G":"A")+"\t"+b.BlockInfoVariantIndex+"\t"+b.MobilIndex+"\t"+b.MobilVariantIndex+"\t"+b.Dir+"\t"+b.CoordX+","+b.CoordY+","+b.CoordZ+"\n");if(seen.Exists(bname))continue;seen.Set(bname,true);auto bi=b.BlockInfo;DumpVariant(bname,"G",0,bi.VariantBaseGround);for(uint k=0;k<bi.AdditionalVariantsGround.Length;k++)DumpVariant(bname,"G",k+1,bi.AdditionalVariantsGround[k]);DumpVariant(bname,"A",0,bi.VariantBaseAir);for(uint k=0;k<bi.AdditionalVariantsAir.Length;k++)DumpVariant(bname,"A",k+1,bi.AdditionalVariantsAir[k]);}f.Write(biOut);f.Close();print("BLOCKINFO done");}
void Main(){while(true){sleep(500);
 {string op=IO::FromDataFolder("openeditor.txt");if(IO::FileExists(op)){string s="";try{IO::File f(op,IO::FileMode::Read);s=f.ReadToEnd();f.Close();}catch{s=lastOpen;}if(s!=lastOpen){lastOpen=s;auto mp=cast<CGameManiaPlanet>(GetApp());if(mp!is null&&mp.ManiaTitleControlScriptAPI!is null){if(s.StartsWith("newmap")){mp.ManiaTitleControlScriptAPI.EditNewMap1("BlueBay","Day64","","","","","");print("OPENEDITOR newmap BlueBay");}else if(s.StartsWith("itemnew")){auto edc=cast<CGameCtnEditorCommon>(GetApp().Editor);if(edc is null){print("OPENEDITOR itemnew: not in map editor");}else{edc.ButtonItemNewModeOnClick();print("OPENEDITOR itemnew");}}else if(s.StartsWith("meshswitch")){auto ie=cast<CGameEditorItem>(GetApp().Editor);if(ie is null){print("OPENEDITOR meshswitch: editor is "+(GetApp().Editor is null?"null":Reflection::TypeOf(GetApp().Editor).Name));}else{ie.SwitchMeshModeler();print("OPENEDITOR meshswitch");}}else if(s.StartsWith("mesh")){mp.ManiaTitleControlScriptAPI.OpenEditor2(CGameManiaTitleControlScriptAPI::EEditorType::MeshModeler);print("OPENEDITOR mesh");}else if(s.StartsWith("item")){mp.ManiaTitleControlScriptAPI.OpenEditor2(CGameManiaTitleControlScriptAPI::EEditorType::ItemEditor);print("OPENEDITOR item");}}}}
  string mt=IO::FromDataFolder("dumpmat.txt");if(IO::FileExists(mt)){string s="";try{IO::File f(mt,IO::FileMode::Read);s=f.ReadToEnd();f.Close();}catch{s=lastMat;}if(s!=lastMat){lastMat=s;auto me=cast<CGameEditorMesh>(GetApp().Editor);if(me is null){auto ie=cast<CGameEditorItem>(GetApp().Editor);print("DUMPMAT: editor is "+(GetApp().Editor is null?"null":Reflection::TypeOf(GetApp().Editor).Name));}else{try{DumpMaterials(me);}catch{print("DUMPMAT failed: "+getExceptionInfo());}}}}}
if(GetApp().CurrentPlayground!is null&&GetApp().Editor is null){string cp=IO::FromDataFolder("carprobe.txt");if(IO::FileExists(cp)){string s="";try{IO::File f(cp,IO::FileMode::Read);s=f.ReadToEnd();f.Close();}catch{s=lastProbe;}if(s!=lastProbe){lastProbe=s;try{CarProbe();}catch{print("CARPROBE failed: "+getExceptionInfo());}}}continue;}auto ed=cast<CGameCtnEditorFree>(GetApp().Editor);if(ed is null||ed.PluginMapType is null)continue;string path=IO::FromDataFolder("cam.txt");if(IO::FileExists(path)){string s="";try{IO::File f(path,IO::FileMode::Read);s=f.ReadToEnd();f.Close();}catch{s=last;}if(s!=last){last=s;auto p=s.Split(",");if(p.Length>=6){vec3 t=vec3(Text::ParseFloat(p[0]),Text::ParseFloat(p[1]),Text::ParseFloat(p[2]));ed.PluginMapType.CameraTargetPosition=t;ed.PluginMapType.CameraToTargetDistance=Text::ParseFloat(p[3]);ed.PluginMapType.CameraHAngle=Text::ParseFloat(p[4]);ed.PluginMapType.CameraVAngle=Text::ParseFloat(p[5]);if(ed.OrbitalCameraControl!is null){ed.OrbitalCameraControl.m_TargetedPosition=t;ed.OrbitalCameraControl.m_CameraToTargetDistance=Text::ParseFloat(p[3]);ed.OrbitalCameraControl.m_CurrentHAngle=Text::ParseFloat(p[4]);ed.OrbitalCameraControl.m_CurrentVAngle=Text::ParseFloat(p[5]);}print("CAMERA "+s);}}}string bp=IO::FromDataFolder("blockinfo.txt");if(IO::FileExists(bp)){string s="";try{IO::File f(bp,IO::FileMode::Read);s=f.ReadToEnd();f.Close();}catch{s=lastBI;}if(s!=lastBI){lastBI=s;try{DumpBlockInfos(ed);}catch{print("BLOCKINFO failed: "+getExceptionInfo());}}}string pp=IO::FromDataFolder("probe.txt");if(IO::FileExists(pp)){string s="";try{IO::File f(pp,IO::FileMode::Read);s=f.ReadToEnd();f.Close();}catch{s=lastProbe;}if(s!=lastProbe){lastProbe=s;try{Probe(ed);}catch{print("PROBE failed: "+getExceptionInfo());}}}}}
